@startuml
title Device Management Service Diagram

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(Gateway, "API Gateway")
Container_Boundary(DeviceManagementSvc, "Device Management Service") {
   Component(CommandController, "Device Command controller", "", "Allow users to send command to their devices")
   Component(DeviceController, "Device controller", "", "Allow users to register and configure their devices")
   Component(CommandHandler, "Command Handler Service", "", "Handle and send commands to device")
   Component(DeviceManagerService, "Device Manager Service", "", "Process and return device configuration")
   Component(SensorManagerFacade, "Sensor Manager Facade", "", "Introduce low-level communication with sensor")
   Component(CommandConsumer, "Kafka commands consumer")
}

ComponentQueue(CommandsQ, "Device Commands topic")
System_Ext(Sensors, "Perception Layer", "System of sensors and edge devices collecting telemetry", $sprite=robot)

Rel(Gateway, CommandController, "Send command", "Rest API")
Rel(Gateway, DeviceController, "Get or update device configuration", "Rest API")
Rel(CommandController, CommandHandler, "Uses")
Rel(DeviceController, DeviceManagerService, "Uses")
Rel(CommandHandler, DeviceManagerService, "Check owner in device configuration")
Rel(CommandHandler, SensorManagerFacade, "Uses")
Rel(SensorManagerFacade, Sensors, "Send command to sensor", "MQTT/CoAp")
Rel(CommandsQ, CommandConsumer, "Apply commands")
Rel(CommandConsumer, CommandHandler, "Uses")

@enduml